export const veganMeals = {
  "meals": [
    {
      "idMeal": "52775",
      "strMeal": "Vegan Lasagna",
      "strDrinkAlternate": null,
      "strCategory": "Vegan",
      "strArea": "Italian",
      "strInstructions": "1) Preheat oven to 180 degrees celcius. \r\n2) Boil vegetables for 5-7 minutes, until soft. Add lentils and bring to a gentle simmer, adding a stock cube if desired. Continue cooking and stirring until the lentils are soft, which should take about 20 minutes. \r\n3) Blanch spinach leaves for a few minutes in a pan, before removing and setting aside. \r\n4) Top up the pan with water and cook the lasagne sheets. When cooked, drain and set aside.\r\n5) To make the sauce, melt the butter and add the flour, then gradually add the soya milk along with the mustard and the vinegar. Cook and stir until smooth and then assemble the lasagne as desired in a baking dish. \r\n6) Bake in the preheated oven for about 25 minutes.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg",
      "strTags": "Vegan,Pasta",
      "strYoutube": "https://www.youtube.com/watch?v=VU8cXvlGbvc",
      "strIngredient1": "green red lentils",
      "strIngredient2": "carrot",
      "strIngredient3": "onion",
      "strIngredient4": "zucchini",
      "strIngredient5": "coriander",
      "strIngredient6": "spinach",
      "strIngredient7": "lasagne sheets",
      "strIngredient8": "vegan butter",
      "strIngredient9": "flour",
      "strIngredient10": "soya milk",
      "strIngredient11": "mustard",
      "strIngredient12": "vinegar",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "1 cups",
      "strMeasure2": "1",
      "strMeasure3": "1",
      "strMeasure4": "1 small",
      "strMeasure5": "sprinking",
      "strMeasure6": "150g",
      "strMeasure7": "10",
      "strMeasure8": "35g",
      "strMeasure9": "4 tablespoons",
      "strMeasure10": "300ml",
      "strMeasure11": "1.5 teaspoons",
      "strMeasure12": "1 teaspoon",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52794",
      "strMeal": "Vegan Chocolate Cake",
      "strDrinkAlternate": null,
      "strCategory": "Vegan",
      "strArea": "American",
      "strInstructions": "Simply mix all dry ingredients with wet ingredients and blend altogether. Bake for 45 min on 180 degrees. Decorate with some melted vegan chocolate ",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg",
      "strTags": "Vegan,Chocolate,Cake",
      "strYoutube": "https://www.youtube.com/watch?v=C3pAgB7pync",
      "strIngredient1": "self raising flour",
      "strIngredient2": "coco sugar",
      "strIngredient3": "cacao",
      "strIngredient4": "baking powder",
      "strIngredient5": "flax eggs",
      "strIngredient6": "almond milk",
      "strIngredient7": "vanilla",
      "strIngredient8": "water",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 1/4 cup",
      "strMeasure2": "1/2 cup",
      "strMeasure3": "1/3 cup raw",
      "strMeasure4": "1 tsp",
      "strMeasure5": "2",
      "strMeasure6": "1/2 cup",
      "strMeasure7": "1 tsp",
      "strMeasure8": "1/2 cup boiling",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
};

export const drinksWithLemon = {
  "drinks": [
    {
      "strDrink": "A True Amaretto Sour",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rptuxy1472669372.jpg",
      "idDrink": "17005"
    },
    {
      "strDrink": "Boston Sour",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/kxlgbi1504366100.jpg",
      "idDrink": "11129"
    },
    {
      "strDrink": "Brandy Cobbler",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5xgu591582580586.jpg",
      "idDrink": "11157"
    },
    {
      "strDrink": "Brandy Sour",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/b1bxgq1582484872.jpg",
      "idDrink": "11170"
    },
    {
      "strDrink": "California Lemonade",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/q5z4841582484168.jpg",
      "idDrink": "11205"
    },
    {
      "strDrink": "Chicago Fizz",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qwvwqr1441207763.jpg",
      "idDrink": "11242"
    },
    {
      "strDrink": "Clover Club",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/t0aja61504348715.jpg",
      "idDrink": "17186"
    },
    {
      "strDrink": "Frisco Sour",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/acuvjz1582482022.jpg",
      "idDrink": "11382"
    },
    {
      "strDrink": "Gin Fizz",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/drtihp1606768397.jpg",
      "idDrink": "11410"
    },
    {
      "strDrink": "Gin Rickey",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/s00d6f1504883945.jpg",
      "idDrink": "17230"
    },
    {
      "strDrink": "Gin Sling",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/8cl9sm1582581761.jpg",
      "idDrink": "11415"
    },
    {
      "strDrink": "Grape lemon pineapple Smoothie",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/54z5h71487603583.jpg",
      "idDrink": "12712"
    },
    {
      "strDrink": "Imperial Fizz",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/zj1usl1504884548.jpg",
      "idDrink": "11524"
    },
    {
      "strDrink": "Japanese Fizz",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/37vzv11504884831.jpg",
      "idDrink": "11558"
    },
    {
      "strDrink": "Kill the cold Smoothie",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/7j1z2e1487603414.jpg",
      "idDrink": "12720"
    },
    {
      "strDrink": "Lemon Drop",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/mtpxgk1504373297.jpg",
      "idDrink": "14366"
    },
    {
      "strDrink": "Lemon Shot",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/mx31hv1487602979.jpg",
      "idDrink": "12752"
    },
    {
      "strDrink": "Lemouroudji",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/eirmo71487603745.jpg",
      "idDrink": "12702"
    },
    {
      "strDrink": "New York Sour",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/61wgch1504882795.jpg",
      "idDrink": "11844"
    },
    {
      "strDrink": "Quaker's Cocktail",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/yrqppx1478962314.jpg",
      "idDrink": "11983"
    },
    {
      "strDrink": "Royal Gin Fizz",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/pe1x1c1504735672.jpg",
      "idDrink": "12057"
    },
    {
      "strDrink": "Rum Cobbler",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5vh9ld1504390683.jpg",
      "idDrink": "12067"
    },
    {
      "strDrink": "Rum Cooler",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2hgwsb1504888674.jpg",
      "idDrink": "12071"
    },
    {
      "strDrink": "Sangria The  Best",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vysywu1468924264.jpg",
      "idDrink": "13026"
    },
    {
      "strDrink": "Sidecar Cocktail",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ewjxui1504820428.jpg",
      "idDrink": "12198"
    },
    {
      "strDrink": "Snowball",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/7ibfs61504735416.jpg",
      "idDrink": "14195"
    },
    {
      "strDrink": "Strawberry Lemonade",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/spvvxp1468924425.jpg",
      "idDrink": "13036"
    },
    {
      "strDrink": "Tequila Sour",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ek0mlq1504820601.jpg",
      "idDrink": "12370"
    },
    {
      "strDrink": "Vesuvio",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/26cq601492976203.jpg",
      "idDrink": "12444"
    },
    {
      "strDrink": "Whiskey Sour",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg",
      "idDrink": "11004"
    },
    {
      "strDrink": "White Wine Sangria",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/hnuod91587851576.jpg",
      "idDrink": "178326"
    },
    {
      "strDrink": "Wine Punch",
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/txustu1473344310.jpg",
      "idDrink": "13058"
    }
  ]
};

export const mealsWithNameLemon = {
  "meals": [
    {
      "idMeal": "53009",
      "strMeal": "Lamb and Lemon Souvlaki",
      "strDrinkAlternate": null,
      "strCategory": "Lamb",
      "strArea": "Greek",
      "strInstructions": "Pound the garlic with sea salt in a pestle and mortar (or use a small food processor), until the garlic forms a paste. Whisk together the oil, lemon juice, zest, dill and garlic. Mix in the lamb and combine well. Cover and marinate for at least 2 hrs or overnight in the fridge. If you’re going to use bamboo skewers, soak them in cold water.\r\n\r\nIf you’ve prepared the lamb the previous day, take it out of the fridge 30 mins before cooking. Thread the meat onto the soaked or metal skewers. Heat the grill to high or have a hot griddle pan or barbecue ready. Cook the skewers for 2-3 mins on each side, basting with the remaining marinade. Heat the pitta or flatbreads briefly, then stuff with the souvlaki. Add Greek salad (see 'Goes well with', right) and Tzatziki (below), if you like.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/rjhf741585564676.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=krR4rhjR75Y",
      "strIngredient1": "Garlic",
      "strIngredient2": "Sea Salt",
      "strIngredient3": "Olive Oil",
      "strIngredient4": "Lemon",
      "strIngredient5": "Dill",
      "strIngredient6": "Lamb Leg",
      "strIngredient7": "Pita Bread",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 cloves",
      "strMeasure2": "2 tsp",
      "strMeasure3": "4 tbs",
      "strMeasure4": "Zest and juice of 1",
      "strMeasure5": "1 tbs",
      "strMeasure6": "750g",
      "strMeasure7": "To serve",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/lamb-lemon-dill-souvlaki",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
};

export const drinksCategory = {
  "drinks": [
    {
      "strCategory": "Ordinary Drink"
    },
    {
      "strCategory": "Cocktail"
    },
    {
      "strCategory": "Shake"
    },
    {
      "strCategory": "Other/Unknown"
    },
    {
      "strCategory": "Cocoa"
    },
    {
      "strCategory": "Shot"
    },
    {
      "strCategory": "Coffee / Tea"
    },
    {
      "strCategory": "Homemade Liqueur"
    },
    {
      "strCategory": "Punch / Party Drink"
    },
    {
      "strCategory": "Beer"
    },
    {
      "strCategory": "Soft Drink"
    }
  ]
};

export const foodsCategory = {
  "meals": [
    { "strCategory": "Beef"
    },
    {
      "strCategory": "Breakfast"
    },
    {
      "strCategory": "Chicken"
    },
    {
      "strCategory": "Dessert"
    },
    {
      "strCategory": "Goat"
    },
    {
      "strCategory": "Lamb"
    },
    {
      "strCategory": "Miscellaneous"
    },
    {
      "strCategory": "Pasta"
    },
    {
      "strCategory": "Pork"
    },
    {
      "strCategory": "Seafood"
    },
    {
      "strCategory": "Side"
    },
    {
      "strCategory": "Starter"
    },
    {
      "strCategory": "Vegan"
    },
    {
      "strCategory": "Vegetarian"
    }
  ]
};

export const mockFoodWithId = {
  "meals": [
    {
      "idMeal": "52771",
      "strMeal": "Spicy Arrabiata Penne",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Italian",
      "strInstructions": "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
      "strTags": "Pasta,Curry",
      "strYoutube": "https://www.youtube.com/watch?v=1IszT_guI08",
      "strIngredient1": "penne rigate",
      "strIngredient2": "olive oil",
      "strIngredient3": "garlic",
      "strIngredient4": "chopped tomatoes",
      "strIngredient5": "red chile flakes",
      "strIngredient6": "italian seasoning",
      "strIngredient7": "basil",
      "strIngredient8": "Parmigiano-Reggiano",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "1 pound",
      "strMeasure2": "1/4 cup",
      "strMeasure3": "3 cloves",
      "strMeasure4": "1 tin ",
      "strMeasure5": "1/2 teaspoon",
      "strMeasure6": "1/2 teaspoon",
      "strMeasure7": "6 leaves",
      "strMeasure8": "spinkling",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
};

export const drinksRecomendation = {
  "drinks": [
    {
      "idDrink": "15997",
      "strDrink": "GG",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Optional alcohol",
      "strGlass": "Collins Glass",
      "strInstructions": "Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.",
      "strInstructionsES": null,
      "strInstructionsDE": "Den Galliano-Likör über Eis gießen. Füllen Sie den Rest des Glases mit Ginger Ale und das ist alles, was dazu gehört. Du hast jetzt ein eigenes GG.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versare il liquore Galliano su ghiaccio.\r\nRiempi il resto del bicchiere con ginger ale e questo è tutto.\r\nOra hai il tuo GG personale.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg",
      "strIngredient1": "Galliano",
      "strIngredient2": "Ginger ale",
      "strIngredient3": "Ice",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 1/2 shots ",
      "strMeasure2": null,
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-07-18 22:06:00"
    },
    {
      "idDrink": "17222",
      "strDrink": "A1",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
      "strInstructionsES": "Vierta todos los ingredientes en una coctelera, mezcle y sirva con hielo en un vaso frío.",
      "strInstructionsDE": "Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg",
      "strIngredient1": "Gin",
      "strIngredient2": "Grand Marnier",
      "strIngredient3": "Lemon Juice",
      "strIngredient4": "Grenadine",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 3/4 shot ",
      "strMeasure2": "1 Shot ",
      "strMeasure3": "1/4 Shot",
      "strMeasure4": "1/8 Shot",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-07 21:42:09"
    },
    {
      "idDrink": "13501",
      "strDrink": "ABC",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Shot",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Shot glass",
      "strInstructions": "Layered in a shot glass.",
      "strInstructionsES": "Coloque todos los ingredientes en un vaso de chupito.",
      "strInstructionsDE": "Schichtaufbau in einem Schnapsglas.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg",
      "strIngredient1": "Amaretto",
      "strIngredient2": "Baileys irish cream",
      "strIngredient3": "Cognac",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/3 ",
      "strMeasure2": "1/3 ",
      "strMeasure3": "1/3 ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-08-31 19:32:08"
    },
    {
      "idDrink": "17203",
      "strDrink": "Kir",
      "strDrinkAlternate": null,
      "strTags": "IBA,ContemporaryClassic",
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Wine Glass",
      "strInstructions": "Add the crème de cassis to the bottom of the glass, then top up with wine.",
      "strInstructionsES": null,
      "strInstructionsDE": "Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg",
      "strIngredient1": "Creme de Cassis",
      "strIngredient2": "Champagne",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 part ",
      "strMeasure2": "5 parts ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-02 17:38:14"
    },
    {
      "idDrink": "14229",
      "strDrink": "747",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Shot",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Shot glass",
      "strInstructions": "pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!",
      "strInstructionsES": null,
      "strInstructionsDE": "Gießen Sie kaluha, dann Baileys, dann Frangelico nicht gekühlt und nicht geschichtet -- SERVE!!!!!!!!",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versa Kahlua, Baileys e poi Frangelico.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg",
      "strIngredient1": "Kahlua",
      "strIngredient2": "Baileys irish cream",
      "strIngredient3": "Frangelico",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/3 part ",
      "strMeasure2": "1/3 part ",
      "strMeasure3": "1/3 part ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-08-31 19:28:26"
    },
    {
      "idDrink": "15288",
      "strDrink": "252",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Shot",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Shot glass",
      "strInstructions": "Add both ingredients to shot glass, shoot, and get drunk quick",
      "strInstructionsES": null,
      "strInstructionsDE": "Beide Zutaten in ein Schnapsglas geben.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Aggiungi entrambi gli ingredienti al bicchierino, bevi e ubriacati velocemente",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg",
      "strIngredient1": "151 proof rum",
      "strIngredient2": "Wild Turkey",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/2 shot Bacardi ",
      "strMeasure2": "1/2 shot ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-07-18 22:32:42"
    },
    {
      "idDrink": "17225",
      "strDrink": "Ace",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Martini Glass",
      "strInstructions": "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
      "strInstructionsES": "Agite todos los ingredientes en una coctelera con hielo y entonces cuélelos sobre un vaso enfriado.",
      "strInstructionsDE": "Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg",
      "strIngredient1": "Gin",
      "strIngredient2": "Grenadine",
      "strIngredient3": "Heavy cream",
      "strIngredient4": "Milk",
      "strIngredient5": "Egg White",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 shots ",
      "strMeasure2": "1/2 shot ",
      "strMeasure3": "1/2 shot ",
      "strMeasure4": "1/2 shot",
      "strMeasure5": "1/2 Fresh",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-07 22:05:06"
    },
  ]
};

export const mockDrinkWithId = {
  "drinks": [
    {
      "idDrink": "178319",
      "strDrink": "Aquamarine",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Martini Glass",
      "strInstructions": "Shake well in a shaker with ice.\r\nStrain in a martini glass.",
      "strInstructionsES": "Agite bien en una coctelera con hielo. Cuela en una copa de Martini.",
      "strInstructionsDE": null,
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare bene in uno shaker con ghiaccio.\r\nFiltrare in una coppetta Martini.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg",
      "strIngredient1": "Hpnotiq",
      "strIngredient2": "Pineapple Juice",
      "strIngredient3": "Banana Liqueur",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz",
      "strMeasure2": "1 oz",
      "strMeasure3": "1 oz",
      "strMeasure4": "",
      "strMeasure5": "",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": null
    }
  ]
};

export const foodsRecomendation = {
  "meals": [
    {
      "idMeal": "52977",
      "strMeal": "Corba",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Turkish",
      "strInstructions": "Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you’ll have to break up later\r\nIn a large pot over medium-high heat, sauté the olive oil and the onion with a pinch of salt for about 3 minutes, then add the carrots and cook for another 3 minutes.\r\nAdd the tomato paste and stir it around for around 1 minute. Now add the cumin, paprika, mint, thyme, black pepper, and red pepper as quickly as you can and stir for 10 seconds to bloom the spices. Congratulate yourself on how amazing your house now smells.\r\nImmediately add the lentils, water, broth, and salt. Bring the soup to a (gentle) boil.\r\nAfter it has come to a boil, reduce heat to medium-low, cover the pot halfway, and cook for 15-20 minutes or until the lentils have fallen apart and the carrots are completely cooked.\r\nAfter the soup has cooked and the lentils are tender, blend the soup either in a blender or simply use a hand blender to reach the consistency you desire. Taste for seasoning and add more salt if necessary.\r\nServe with crushed-up crackers, torn up bread, or something else to add some extra thickness.  You could also use a traditional thickener (like cornstarch or flour), but I prefer to add crackers for some texture and saltiness.  Makes great leftovers, stays good in the fridge for about a week.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/58oia61564916529.jpg",
      "strTags": "Soup",
      "strYoutube": "https://www.youtube.com/watch?v=VVnZd8A84z4",
      "strIngredient1": "Lentils",
      "strIngredient2": "Onion",
      "strIngredient3": "Carrots",
      "strIngredient4": "Tomato Puree",
      "strIngredient5": "Cumin",
      "strIngredient6": "Paprika",
      "strIngredient7": "Mint",
      "strIngredient8": "Thyme",
      "strIngredient9": "Black Pepper",
      "strIngredient10": "Red Pepper Flakes",
      "strIngredient11": "Vegetable Stock",
      "strIngredient12": "Water",
      "strIngredient13": "Sea Salt",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 cup ",
      "strMeasure2": "1 large",
      "strMeasure3": "1 large",
      "strMeasure4": "1 tbs",
      "strMeasure5": "2 tsp",
      "strMeasure6": "1 tsp ",
      "strMeasure7": "1/2 tsp",
      "strMeasure8": "1/2 tsp",
      "strMeasure9": "1/4 tsp",
      "strMeasure10": "1/4 tsp",
      "strMeasure11": "4 cups ",
      "strMeasure12": "1 cup ",
      "strMeasure13": "Pinch",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53060",
      "strMeal": "Burek",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Croatian",
      "strInstructions": "Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
      "strTags": "Streetfood, Onthego",
      "strYoutube": "https://www.youtube.com/watch?v=YsJXZwE5pdY",
      "strIngredient1": "Filo Pastry",
      "strIngredient2": "Minced Beef",
      "strIngredient3": "Onion",
      "strIngredient4": "Oil",
      "strIngredient5": "Salt",
      "strIngredient6": "Pepper",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 Packet",
      "strMeasure2": "150g",
      "strMeasure3": "150g",
      "strMeasure4": "40g",
      "strMeasure5": "Dash",
      "strMeasure6": "Dash",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52978",
      "strMeal": "Kumpir",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Turkish",
      "strInstructions": "If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer.\r\n\r\nGrate (roughly – you can use as much as you like) 150g of cheese.\r\nFinely chop one onion and one sweet red pepper.\r\nPut these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional).",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg",
      "strTags": "SideDish",
      "strYoutube": "https://www.youtube.com/watch?v=IEDEtZ4UVtI",
      "strIngredient1": "Potatoes",
      "strIngredient2": "Butter",
      "strIngredient3": "Cheese",
      "strIngredient4": "Onion",
      "strIngredient5": "Red Pepper",
      "strIngredient6": "Red Chile Flakes",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 large",
      "strMeasure2": "2 tbs",
      "strMeasure3": "150g",
      "strMeasure4": "1 large",
      "strMeasure5": "1 large",
      "strMeasure6": "Pinch",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53026",
      "strMeal": "Tamiya",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Egyptian",
      "strInstructions": "oak the beans in water to cover overnight.Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder.If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 minutes.\r\nShape the bean mixture into 1-inch balls.Flatten slightly and coat with flour.\r\nHeat at least 1½-inches of oil over medium heat to 365 degrees.\r\nFry the patties in batches, turning once, until golden brown on all sides, about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=mulqW-J3Yy4",
      "strIngredient1": "Broad Beans",
      "strIngredient2": "Spring Onions",
      "strIngredient3": "Garlic Clove",
      "strIngredient4": "Parsley",
      "strIngredient5": "Cumin",
      "strIngredient6": "Baking Powder",
      "strIngredient7": "Cayenne Pepper",
      "strIngredient8": "Flour",
      "strIngredient9": "Vegetable Oil",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 cups ",
      "strMeasure2": "6",
      "strMeasure3": "4",
      "strMeasure4": "1/4 cup",
      "strMeasure5": "2 tsp",
      "strMeasure6": "1 tsp ",
      "strMeasure7": "1/2 tsp",
      "strMeasure8": "Spinkling",
      "strMeasure9": "As required",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52785",
      "strMeal": "Dal fry",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Indian",
      "strInstructions": "Wash and soak toor dal in approx. 3 cups of water, for at least one hours. Dal will be double in volume after soaking. Drain the water.\r\nCook dal with 2-1/2 cups water and add salt, turmeric, on medium high heat, until soft in texture (approximately 30 mins) it should be like thick soup.\r\nIn a frying pan, heat the ghee. Add cumin seeds, and mustard seeds. After the seeds crack, add bay leaves, green chili, ginger and chili powder. Stir for a few seconds.\r\nAdd tomatoes, salt and sugar stir and cook until tomatoes are tender and mushy.\r\nAdd cilantro and garam masala cook for about one minute.\r\nPour the seasoning over dal mix it well and cook for another minute.\r\nServe with Naan.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
      "strTags": "Curry,Vegetarian,Cake",
      "strYoutube": "https://www.youtube.com/watch?v=J4D855Q9-jg",
      "strIngredient1": "Toor dal",
      "strIngredient2": "Water",
      "strIngredient3": "Salt",
      "strIngredient4": "Turmeric",
      "strIngredient5": "Ghee",
      "strIngredient6": "Chopped tomatoes",
      "strIngredient7": "Cumin seeds",
      "strIngredient8": "Mustard Seeds",
      "strIngredient9": "Bay Leaf",
      "strIngredient10": "Green Chili",
      "strIngredient11": "Ginger",
      "strIngredient12": "Cilantro",
      "strIngredient13": "Red Pepper",
      "strIngredient14": "Salt",
      "strIngredient15": "Sugar",
      "strIngredient16": "Garam Masala",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 cup",
      "strMeasure2": "2-1/2 cups",
      "strMeasure3": "1 tsp",
      "strMeasure4": "1/4 tsp",
      "strMeasure5": "3 tbs",
      "strMeasure6": "1 cup",
      "strMeasure7": "1/2 tsp",
      "strMeasure8": "1/2 tsp",
      "strMeasure9": "2",
      "strMeasure10": "1 tbs chopped",
      "strMeasure11": "2 tsp shredded",
      "strMeasure12": "2 tbs ",
      "strMeasure13": "1/2 tsp",
      "strMeasure14": "1/2 tsp",
      "strMeasure15": "1 tsp",
      "strMeasure16": "1/4 tsp",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.instagram.com/p/BO21bpYD3Fu",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52804",
      "strMeal": "Poutine",
      "strDrinkAlternate": null,
      "strCategory": "Miscellaneous",
      "strArea": "Canadian",
      "strInstructions": "Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\nWarm gravy in saucepan or microwave.\r\nPlace the fries into the hot oil, and cook until light brown, about 5 minutes.\r\nRemove to a paper towel lined plate to drain.\r\nPlace the fries on a serving platter, and sprinkle the cheese over them.\r\nLadle gravy over the fries and cheese, and serve immediately.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg",
      "strTags": "UnHealthy,Speciality,HangoverFood",
      "strYoutube": "https://www.youtube.com/watch?v=UVAMAoA2_WU",
      "strIngredient1": "Vegetable Oil",
      "strIngredient2": "Beef Gravy",
      "strIngredient3": "Potatoes",
      "strIngredient4": "Cheese Curds",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "Dash",
      "strMeasure2": "1 Can",
      "strMeasure3": "5 thin cut",
      "strMeasure4": "2 cups",
      "strMeasure5": "",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": "",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.food.com/recipe/real-canadian-poutine-113388",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
  ]
};

export const drinksWithLetterY = {
  "drinks": [
    {
      "idDrink": "17219",
      "strDrink": "Yellow Bird",
      "strDrinkAlternate": null,
      "strTags": "IBA,NewEra",
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": "New Era Drinks",
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Shake and strain into a chilled cocktail glass",
      "strInstructionsES": null,
      "strInstructionsDE": "In ein gekühltes Cocktailglas schütteln und abseihen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare e filtrare in una coppetta da cocktail ghiacciata",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2t9r6w1504374811.jpg",
      "strIngredient1": "White Rum",
      "strIngredient2": "Galliano",
      "strIngredient3": "Triple Sec",
      "strIngredient4": "Lime Juice",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "3 cl",
      "strMeasure2": "1.5 cl",
      "strMeasure3": "1.5 cl",
      "strMeasure4": "1.5 cl",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-02 18:53:31"
    },
    {
      "idDrink": "12728",
      "strDrink": "Yoghurt Cooler",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Other/Unknown",
      "strIBA": null,
      "strAlcoholic": "Non alcoholic",
      "strGlass": "Highball Glass",
      "strInstructions": "Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up. Note: Use lots of ice in this one - great on hot days! To add ice: Remove the center of the cover while the blender is on - drop 3 or 4 ice cubs and blend until they're completely crushed.",
      "strInstructionsES": null,
      "strInstructionsDE": "Alle Zutaten in den Mixer geben - abdecken und bei mittlerer Geschwindigkeit schaumig schlagen, bis sie gut vermischt sind. In ein großes, 2 mittlere oder 3 kleine Gläser füllen und geniessen. Hinweis: Verwenden Sie viel Eis in diesem Gerät - ideal an heißen Tagen! Um Eis hinzuzufügen: Entfernen Sie die Mitte der Abdeckung, während der Mixer eingeschaltet ist - lassen Sie 3 oder 4 Eiswürfel fallen und mischen Sie sie, bis sie vollständig zerkleinert sind.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Mettere tutti gli ingredienti nella caraffa del frullatore - coprire e montare a velocità media fino a quando non sono ben amalgamati.Nota: usa molto ghiaccio in questo - ottimo nelle giornate calde!Versare in un bicchiere alto, 2 medi o 3 piccoli e bere.Per aggiungere il ghiaccio: rimuovere il centro del coperchio mentre il frullatore è acceso - far cadere 3 o 4 cubetti di ghiaccio e frullare fino a quando non saranno completamente schiacciati.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/trttrv1441254466.jpg",
      "strIngredient1": "Yoghurt",
      "strIngredient2": "Fruit",
      "strIngredient3": "Ice",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 cup ",
      "strMeasure2": "1 cup ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-03 05:27:46"
    }
  ]
};
