export { default as DrinkList } from './DrinkList';
export { default as Footer } from './Footer';
// export { default as Header } from './Header';
// export { default as HeaderSearchIcon } from './HeaderSearchIcon';
export { default as MealList } from './MealList';
// export { default as SearchBar } from './SearchBar';
export { default as Slider } from './Slider';
export { default as FavoriteButton } from './FavoriteButton';
export { default as StartRecipeButton } from './StartRecipeButton';
export { default as MealsDetails } from './MealsDetails';
export { default as DrinkDetails } from './DrinkDetails';
